'use client';

import Image from "next/image";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/Sidebar";
import { useState } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-wrapper">
          <header className="page-header">
            <button className="hamburger" onClick={() => setSidebarOpen(true)}>
              <Image
                src="icons/menu.svg"
                alt="Menu"
                width={24}
                height={24}
              />
            </button>
            <h1 className="page-title">Ratings Project</h1>
            <h1 className="page-login">Log in</h1>
          </header>

          <div className="layout">
            <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />
            <main className="main-content">{children}</main>
          </div>

          <footer className="website-footer">Footer</footer>
        </div>
      </body>
    </html>
  );
}
